repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Format code with Black
        language: python
        types: [python]
        args: [--line-length=120]
        stages: [pre-commit, commit]
        additional_dependencies: []
        require_serial: false
        verbose: true