version: "3.8"

services:
  controller:
    build:
      context: grpc_server/controller
      dockerfile: Dockerfile.controller
    volumes:
      - /run/controller:/run/controller
    restart: always
    logging:
        driver: loki
        options:
          loki-timeout: 10s
          no-file: "true"
          loki-url:  "http://172.29.0.2:3100/loki/api/v1/push"
          loki-pipeline-stages: |
            - regex:
                expression: '(level|lvl|severity)=(?P<level>\w+)'
            - labels:
                level: level

  replicated_worker:
    build:
      context: grpc_server/controller
      dockerfile: Dockerfile.worker
    volumes:
      - /run/controller:/run/controller
    depends_on:
      - controller
    restart: always
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-3}
    logging:
        driver: loki
        options:
          loki-timeout: 10s
          no-file: "true"
          loki-url:  "http://172.29.0.2:3100/loki/api/v1/push"
          loki-pipeline-stages: |
            - regex:
                expression: '(level|lvl|severity)=(?P<level>\w+)'
            - labels:
                level: level
