global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'cluster'
    static_configs:
      - targets: ['client1:9273', 'client2:9273']
