server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    external_labels:
      job: my_app
      env: development

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [localhost]
        labels:
          job: my_app
          __path__: /var/log/**/*.log

  - job_name: docker_containers
    static_configs:
      - targets: [localhost]
        labels:
          job: my_app
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: custom_app
    static_configs:
      - targets: [localhost]
        labels:
          job: my_app
          __path__: /app/logs/*.log