services:
    cpp-app:
      build: 
        context: .
        dockerfile: Dockerfile.app_cpp
      logging:
        driver: loki
        options:
          loki-timeout: 10s
          no-file: "true"
          loki-external-labels: "container_name={{.Name}}"
          labels: "container_name, host"
          loki-url:  "http://172.29.0.2:3100/loki/api/v1/push"
    err-cpp:
      build:
        context: .
        dockerfile: Dockerfile.err_cpp
      logging:
        driver: loki
        options:
          loki-url:  "http://172.29.0.2:3100/loki/api/v1/push" 
    logging_app:
      build: 
        context: .
        dockerfile: Dockerfile.python
      container_name: logging_app
      restart: unless-stopped
      logging:
        driver: loki
        options:
          loki-url:  "http://172.29.0.2:3100/loki/api/v1/push"
          loki-pipeline-stages: |
            - regex:
                expression: '(level|lvl|severity)=(?P<level>\w+)'
            - labels:
                level: level
      environment:
        - PYTHONUNBUFFERED=1
