services:
  loki:
    image: grafana/loki:2.9.4
    user: root
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./data/loki/data:/tmp/loki
      - ./configs/loki/loki.yml:/mnt/loki-local-config.yaml
    networks:
      logging_net:
        ipv4_address: 172.29.0.2
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki 
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./configs/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      logging_net:
        ipv4_address: 172.29.0.3

networks:
  logging_net:
    ipam:
      config:
        - subnet: 172.29.0.0/16
    