name: Flake8 check (style check)

on: [push]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Linters
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        path: "src"